import pandas as pd
from typing import Dict, Optional


class AnalysisAgent:
    """
    Generic, domain-aware data analysis agent.

    Uses DomainConfigAgent output to dynamically determine:
    - Important metrics
    - Dimensions
    - Summary statistics
    - Top values
    - Grouped performance
    - Trends over time
    """

    def __init__(self):
        self.name = "AnalysisAgent"

    def analyze(
        self,
        df: pd.DataFrame,
        config: Optional[Dict] = None
    ) -> Dict:
        """
        Analyze a cleaned dataset dynamically.

        Args:
            df: Cleaned pandas DataFrame.
            config: Domain configuration generated by
                    DomainConfigAgent.

        Returns:
            Dictionary containing analysis insights.
        """

        print(f"\n{'=' * 60}")
        print("ANALYSIS AGENT: Starting data analysis")
        print(f"{'=' * 60}")

        # ---------------------------------------------------------
        # VALIDATE DATA
        # ---------------------------------------------------------
        if df is None or df.empty:
            return {
                "agent": self.name,
                "status": "error",
                "error": "Dataset is empty after cleaning."
            }

        # ---------------------------------------------------------
        # READ DOMAIN CONFIGURATION
        # ---------------------------------------------------------
        config = config or {}

        domain = config.get(
            "domain",
            "general business analytics"
        )

        dataset_profile = config.get(
            "dataset_profile",
            {}
        )

        configured_metrics = config.get(
            "metric_columns",
            []
        )

        configured_dimensions = config.get(
            "dimension_columns",
            []
        )

        configured_success_metrics = config.get(
            "success_metrics",
            []
        )

        # ---------------------------------------------------------
        # GET VALID METRIC COLUMNS
        # ---------------------------------------------------------
        metric_columns = [
            column
            for column in configured_metrics
            if column in df.columns
            and pd.api.types.is_numeric_dtype(
                df[column]
            )
        ]

        # ---------------------------------------------------------
        # GET VALID DIMENSION COLUMNS
        # ---------------------------------------------------------
        dimension_columns = [
            column
            for column in configured_dimensions
            if column in df.columns
        ]

        # ---------------------------------------------------------
        # GET DATETIME COLUMNS
        # ---------------------------------------------------------
        datetime_columns = [
            column
            for column in dataset_profile.get(
                "datetime_columns",
                []
            )
            if column in df.columns
        ]

        # ---------------------------------------------------------
        # FALLBACK METRIC DETECTION
        # ---------------------------------------------------------
        if not metric_columns:

            metric_columns = [
                column
                for column in df.columns
                if pd.api.types.is_numeric_dtype(
                    df[column]
                )
            ]

        # ---------------------------------------------------------
        # FALLBACK DIMENSION DETECTION
        # ---------------------------------------------------------
        if not dimension_columns:

            dimension_columns = [
                column
                for column in df.columns
                if (
                    not pd.api.types.is_numeric_dtype(
                        df[column]
                    )
                    and column not in datetime_columns
                )
            ]

        # ---------------------------------------------------------
        # REMOVE DATETIME COLUMNS FROM DIMENSIONS
        # ---------------------------------------------------------
        dimension_columns = [
            column
            for column in dimension_columns
            if column not in datetime_columns
        ]

        # ---------------------------------------------------------
        # BASIC DATASET SUMMARY
        # ---------------------------------------------------------
        summary = {
            "total_records": int(len(df)),
            "total_columns": int(len(df.columns)),
            "columns": list(df.columns),
            "domain": domain
        }

        # ---------------------------------------------------------
        # METRIC STATISTICS
        # ---------------------------------------------------------
        metric_statistics = {}

        for column in metric_columns:

            try:

                series = pd.to_numeric(
                    df[column],
                    errors="coerce"
                ).dropna()

                if series.empty:
                    continue

                metric_statistics[column] = {
                    "total": float(series.sum()),
                    "average": float(series.mean()),
                    "minimum": float(series.min()),
                    "maximum": float(series.max()),
                    "median": float(series.median())
                }

            except Exception:
                continue

        # ---------------------------------------------------------
        # TOP VALUES BY DIMENSION
        # ---------------------------------------------------------
        top_values = {}

        for dimension in dimension_columns:

            if dimension not in df.columns:
                continue

            try:

                value_counts = (
                    df[dimension]
                    .value_counts()
                    .head(5)
                )

                top_values[dimension] = {
                    str(key): int(value)
                    for key, value
                    in value_counts.items()
                }

            except Exception:
                continue

        # ---------------------------------------------------------
        # SELECT PRIMARY METRIC
        # ---------------------------------------------------------
        primary_metric = self._select_primary_metric(
            metric_columns,
            configured_success_metrics
        )

        # ---------------------------------------------------------
        # GROUPED METRIC ANALYSIS
        # ---------------------------------------------------------
        grouped_analysis = {}

        if primary_metric:

            for dimension in dimension_columns:

                if dimension == primary_metric:
                    continue

                try:

                    grouped = (
                        df.groupby(dimension)[
                            primary_metric
                        ]
                        .sum()
                        .sort_values(
                            ascending=False
                        )
                        .head(10)
                    )

                    grouped_analysis[dimension] = {
                        str(key): float(value)
                        for key, value
                        in grouped.items()
                    }

                except Exception:
                    continue

        # ---------------------------------------------------------
        # TIME TREND ANALYSIS
        # ---------------------------------------------------------
        time_trend = {}

        if datetime_columns and primary_metric:

            date_column = datetime_columns[0]

            try:

                temp_df = df[
                    [date_column, primary_metric]
                ].copy()

                temp_df[date_column] = pd.to_datetime(
                    temp_df[date_column],
                    errors="coerce"
                )

                temp_df = temp_df.dropna(
                    subset=[date_column]
                )

                if not temp_df.empty:

                    temp_df["period"] = (
                        temp_df[date_column]
                        .dt.to_period("M")
                        .astype(str)
                    )

                    trend = (
                        temp_df
                        .groupby("period")[
                            primary_metric
                        ]
                        .sum()
                        .sort_index()
                    )

                    time_trend = {
                        str(key): float(value)
                        for key, value
                        in trend.items()
                    }

            except Exception:
                time_trend = {}

        # ---------------------------------------------------------
        # SUCCESS METRICS
        # ---------------------------------------------------------
        success_metric_results = {}

        for success_metric in configured_success_metrics:

            metric_lower = str(
                success_metric
            ).lower()

            # -----------------------------------------------------
            # TOTAL / SALES / REVENUE
            # -----------------------------------------------------
            if (
                "total" in metric_lower
                or "revenue" in metric_lower
                or "sales" in metric_lower
            ):

                if primary_metric:

                    try:

                        success_metric_results[
                            success_metric
                        ] = float(
                            pd.to_numeric(
                                df[primary_metric],
                                errors="coerce"
                            ).sum()
                        )

                    except Exception:
                        continue

            # -----------------------------------------------------
            # AVERAGE
            # -----------------------------------------------------
            elif "average" in metric_lower:

                if primary_metric:

                    try:

                        success_metric_results[
                            success_metric
                        ] = float(
                            pd.to_numeric(
                                df[primary_metric],
                                errors="coerce"
                            ).mean()
                        )

                    except Exception:
                        continue

            # -----------------------------------------------------
            # TOP / BEST VALUES
            # -----------------------------------------------------
            elif (
                "top" in metric_lower
                or "best" in metric_lower
            ):

                if dimension_columns:

                    dimension = dimension_columns[0]

                    try:

                        counts = (
                            df[dimension]
                            .value_counts()
                            .head(5)
                        )

                        success_metric_results[
                            success_metric
                        ] = {
                            str(key): int(value)
                            for key, value
                            in counts.items()
                        }

                    except Exception:
                        continue

        # ---------------------------------------------------------
        # BUILD FINAL INSIGHTS
        # ---------------------------------------------------------
        insights = {
            "agent": self.name,
            "status": "success",
            "domain": domain,
            "summary": summary,
            "metric_columns": metric_columns,
            "dimension_columns": dimension_columns,
            "datetime_columns": datetime_columns,
            "primary_metric": primary_metric,
            "metric_statistics": metric_statistics,
            "top_values": top_values,
            "grouped_analysis": grouped_analysis,
            "time_trend": time_trend,
            "success_metrics": success_metric_results
        }

        # ---------------------------------------------------------
        # PRINT RESULTS
        # ---------------------------------------------------------
        print("\nANALYSIS SUMMARY:")

        print(
            f"  - Domain: {domain}"
        )

        print(
            f"  - Records: {len(df)}"
        )

        print(
            f"  - Numeric metrics: "
            f"{metric_columns}"
        )

        print(
            f"  - Dimensions: "
            f"{dimension_columns}"
        )

        print(
            f"  - Datetime columns: "
            f"{datetime_columns}"
        )

        if primary_metric:

            print(
                f"  - Primary metric: "
                f"{primary_metric}"
            )

        # ---------------------------------------------------------
        # PRINT METRIC STATISTICS
        # ---------------------------------------------------------
        if metric_statistics:

            print("\nMETRIC STATISTICS:")

            for metric, stats in (
                metric_statistics.items()
            ):

                print(
                    f"  - {metric}: "
                    f"total={stats['total']:.2f}, "
                    f"average={stats['average']:.2f}, "
                    f"min={stats['minimum']:.2f}, "
                    f"max={stats['maximum']:.2f}"
                )

        # ---------------------------------------------------------
        # PRINT GROUPED ANALYSIS
        # ---------------------------------------------------------
        if grouped_analysis:

            print("\nGROUPED ANALYSIS:")

            for dimension, values in (
                grouped_analysis.items()
            ):

                print(
                    f"  - By {dimension}: "
                    f"{values}"
                )

        # ---------------------------------------------------------
        # PRINT TIME TREND
        # ---------------------------------------------------------
        if time_trend:

            print(
                f"\nTIME TREND: "
                f"{len(time_trend)} periods detected"
            )

        print(
            "\n✓ Analysis complete!"
        )

        return insights

    # =============================================================
    # PRIMARY METRIC SELECTION
    # =============================================================

    def _select_primary_metric(
        self,
        metric_columns,
        success_metrics
    ):
        """
        Select the most meaningful numeric metric.

        Preference:
        1. Sales
        2. Revenue
        3. Amount
        4. Total
        5. Value
        6. Price
        7. Income
        8. Profit
        9. MRR
        10. ARR
        11. First available numeric metric
        """

        if not metric_columns:
            return None

        priority_keywords = [
            "sales",
            "revenue",
            "amount",
            "total",
            "value",
            "price",
            "income",
            "profit",
            "mrr",
            "arr"
        ]

        # ---------------------------------------------------------
        # SEMANTIC MATCHING
        # ---------------------------------------------------------
        for keyword in priority_keywords:

            for column in metric_columns:

                if keyword in column.lower():

                    return column

        # ---------------------------------------------------------
        # FALLBACK
        # ---------------------------------------------------------
        return metric_columns[0]